---

- name: Configure /etc/slurm/accounting.conf
  ansible.builtin.lineinfile:
    path: /etc/slurm/accounting.conf
    regex: "^{{ item.name }}="
    line: "{{ item.name }}={{ item.value }}"
  loop: "{{ configure_slurmdbd_accounting_conf }}"
  become: true

- name: Configure /etc/slurm/slurmdbd.conf
  block:

    # For whatever reasons, using file does not exists, there may be some tricks to generate the symlink
    - name: Create slurmdbd.conf from example file
      ansible.builtin.command:
        cmd: "sudo cp /etc/slurm/slurmdbd.conf.example /sched/{{ configure_slurmdb_cluster_name }}/slurmdbd.conf"
        creates: "/sched/{{ configure_slurmdb_cluster_name }}/slurmdbd.conf"
      when: ('/sched', cluster_name, 'slurmdbd.conf') | path_join | string is not exists

    - name: Create slurmdbd.conf symlink in /etc/slurm
      ansible.builtin.file:
        src: "/sched/{{ configure_slurmdb_cluster_name }}/slurmdbd.conf"
        dest: /etc/slurm/slurmdbd.conf
        owner: 'root'
        group: 'root'
        state: "link"
      when: "'/etc/slurm/slurmdbd.conf' is not exists"

    - name: Configure slurm.conf
      ansible.builtin.lineinfile:
        path: /etc/slurm/slurm.conf
        regex: '^#?JobAcctGatherType='
        line: "JobAcctGatherType=jobacct_gather/cgroup"

    - name: Configure slurmdbd.conf
      ansible.builtin.lineinfile:
        path: /etc/slurm/slurmdbd.conf
        regex: '^#?{{ item.name }}='
        line: "{{ item.name }}={{ item.value }}"
      loop: "{{ configure_slurmdb_slurmdbd_conf }}"

    - name: Setup SlurmDBD var directory
      ansible.builtin.file:
        path: "{{ item }}"
        group: 'slurm'
        owner: 'slurm'
        mode: '0755'
        state: "directory"
      loop: "{{ configure_slurmdb_var_directories }}"
  become: true