---

- hosts: all
  
  tasks:

  - name: Ansible facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Print the package facts
    ansible.builtin.debug:
      var: ansible_facts.packages

