---

- hosts: all
  
  tasks:

    - name: "Install software on {{scheduler_id}}"
      when: ansible_facts["hostname"] == scheduler_id
      block:

      - name: Set default Java for Nextflow
        include_role:
          name: set_default_java

      - name: Install Nextflow
        include_role:
          name: install_nextflow

      - name: Install softwares
        include_role:
          name: install_software
