---

configure_slurmdb_sheduler_name: "{{ scheduler_id }}"
configure_slurmdb_mysql_port: "{{ mysql_dbport }}"

configure_slurmdb_slurm_conf:
  - name: 'JobAcctGatherType'
    value: 'jobacct_gather/linux'
  - name: 'PriorityWeightAge'
    value: 1000
  - name: 'PriorityWeightFairshare'
    value: 10000
  - name: 'PriorityWeightJobSize'
    value: 1000
  - name: 'PriorityWeightPartition'
    value: 1000
  - name: 'PriorityWeightQOS'
    value: 0
  - name: 'PriorityType'
    value: 'priority/multifactor'
  - name: 'PriorityDecayHalfLife'
    value: '7-0'
  - name: 'PriorityFavorSmall'
    value: 'YES'
  - name: 'PriorityFlags'
    value: 'SMALL_RELATIVE_TO_TIME'
  - name: 'PriorityMaxAge'
    value: '7-0'

configure_slurmdb_accounting_conf:
  - name: 'AccountingStorageType'
    value: 'accounting_storage/slurmdbd'
  - name: 'JobCompType'
    value: 'jobcomp/mysql'
  - name: 'JobCompUser'
    value: 'slurm'
  - name: 'JobCompPass'
    value: "{{ configure_slurmdb_password | quote }}"

configure_slurmdb_slurmdbd_conf:
  - name: 'StoragePort'
    value: "{{ configure_slurmdb_mysql_port }}"
  - name: 'StoragePass'
    value: "{{ configure_slurmdb_password | quote }}"
  - name: 'PidFile'
    value: '/var/run/slurmdbd/slurmdbd.pid'

configure_slurmdb_var_directories:
  - '/var/log/slurm'
  - '/var/run/slurmdbd'
