---

- name: Get list of nodes in partition
  ansible.builtin.command:
    cmd: scontrol show partition dynamic
  register: scontrol_show_partition
  changed_when: scontrol_show_partition.rc != 0

- name: Set list of nodes
  ansible.builtin.set_fact:
    dynamic_node_list: "{{ item | split('=') | last | split(',') }}" 
  loop: "{{ scontrol_show_partition.stdout_lines }}"
  when: item is match("\s*Nodes")

- name: Debug 1
  ansible.builtin.debug:
    var: dynamic_node_list

- name: Delete current sets of nodes
  ansible.builtin.debug:
    msg: "scontrol delete {{ item }}"
  loop: "{{ dynamic_node_list }}"

# - name: Delete current sets of nodes
#   ansible.builtin.command:
#     cmd: "scontrol delete node {{ item }}"
#   loop: "{{ dynamic_node_list }}"
#   become: true
#   when: "item  != '(null)'"

- name: Create new sets of nodes
  ansible.builtin.debug:
    msg: "scontrol create nodename=ukdri-cluster2-{{ configure_dynamic_partition_suffix }}{{ item.cpus }}-[1-{{ item.quantity }}] Feature=dyn,{{ item.name }} cpus={{ item.cpus }} State=CLOUD RealMemory={{ (item.cpus * 2048 * 0.95) | int }}"
  loop: "{{ configure_dynamic_partition_node_type }}"

# - name: Create new sets of nodes
#   ansible.builtin.command:
#     cmd: "scontrol create nodename=ukdri-cluster2-{{ configure_dynamic_partition_suffix }}{{ item.cpus }}-[1-{{ item.quantity }}] Feature=dyn,{{ item.name }} cpus={{ item.cpus }} State=CLOUD RealMemory={{ (item.cpus * 2048 * 0.95) | int }}"
#   loop: "{{ configure_dynamic_partition_node_type }}"
#   become: true