---

- name: Install Java 17 if not present
  ansible.builtin.dnf:
    name: "{{java_yum_package_name}}"
    state: "present"
    install_weak_deps: false
  become: true

- name: Retrieve Java version
  ansible.builtin.shell: java -version
  register: default_java_version
  changed_when: false

- name: "Set default Java if not version {{java_version}}"
  when: default_java_version.stderr_lines | regex_search('version [^0-9]?([0-9.]+)', '\\1') | first is version(java_version, '<')
  block:
    - name: Get java binary path
      ansible.builtin.shell: "rpm -ql {{java_yum_package_name}}"
      register: java_package_list

    - name: Set Java 17 as default
      ansible.builtin.shell: "alternatives --set java {{java_package_list.stdout_lines |regex_search('[a-zA-Z0-9/.\\-_]+/bin/java')}}"
      become: true

