---

- name: Create Nextflow config directory
  ansible.builtin.file:
    name: "{{ configure_nextflow_config_path }}"
    state: directory
    mode: "775"
    group: "cyclecloud"

- name: Copy Nextflow config file
  ansible.builtin.copy:
    src: "files/config"
    dest: "{{ configure_nextflow_config_path }}/config"
    group: "cyclecloud"
    mode: "664"
    backup: true
  
- name: Copy parameter files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ configure_nextflow_config_path }}/{{ item | basename }}"
    group: "cyclecloud"
    mode: "664"
    backup: true
  with_fileglob: "files/*.config"
  
- name: Copy workflow config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ configure_nextflow_config_path }}/{{ item | basename }}"
    group: "cyclecloud"
    mode: "664"
    backup: true
  with_fileglob: "files/*-params.yml"