---

- name: Create Nextflow config directory
  ansible.builtin.file:
    name: "{{ configure_nextflow_config_path }}"
    state: directory
    mode: "775"
    group: "cyclecloud"

- name: Copy Nextflow config file
  ansible.builtin.template:
    src: "templates/config.j2"
    dest: "{{ configure_nextflow_config_path }}/config"
    mode: '0664'
    group: 'cyclecloud'
  vars:
    config_files: "{{ query('fileglob', 'files/*.config') }}"
  
- name: Copy parameter files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ configure_nextflow_config_path }}/{{ item | basename }}"
    group: "cyclecloud"
    mode: "664"
    backup: true
  with_fileglob: "files/*.config"
  
- name: Copy workflow config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ configure_nextflow_config_path }}/{{ item | basename }}"
    group: "cyclecloud"
    mode: "664"
    backup: true
  with_fileglob: "files/*-params.yml"