---

- name: Execute MySQL command
  ansible.builtin.command:
    cmd: |
      mysql -h {{ mysql_command_host }} -P {{ mysql_command_port }} -u {{ mysql_command_user }}
      {{ (mysql_command_password is defined) | ternary((('-p', (mysql_command_password | default(''))) | join('')), '') }}
      -e "{{ mysql_command_cmd | join(';') }}"
  register: mysql_command_out
  changed_when: mysql_command_out.stdout in 'Query OK'
