---

- name: Restart SlurmDBD
  ansible.builtin.systemd:
    name: 'slurmdbd'
    state: 'restarted'
  register: slurmdbd_systemctl
  failed_when: slurmdbd_systemctl.status.ActiveState != 'active'
  become: true

- name: Restart SlurmCtlD
  ansible.builtin.systemd:
    name: 'slurmctld'
    state: 'restarted'
  register: slurmctld_systemctl
  failed_when: slurmctld_systemctl.status.ActiveState != 'active'
  become: true
